"""Generate editable SVG figures from the demo's JSON evidence."""
import json
from html import escape
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
OUT=ROOT/'docs/assets'
BG='#0b1220'; PANEL='#121e31'; TEXT='#e2e8f0'; MUTED='#aebed4'; BLUE='#38bdf8'
def text(x,y,value,size=18,color=TEXT):
    return f'<text x="{x}" y="{y}" fill="{color}" font-size="{size}" font-family="Arial,sans-serif">{escape(str(value))}</text>'
def rect(x,y,w,h,color=PANEL):
    return f'<rect x="{x}" y="{y}" width="{w}" height="{h}" rx="14" fill="{color}"/>'
def save(name,parts,height=540):
    svg=f'<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="{height}" viewBox="0 0 1200 {height}" role="img"><title>{escape(name.replace("-"," "))}</title>'+rect(0,0,1200,height,BG)+''.join(parts)+'</svg>'
    (OUT/f'{name}.svg').write_text(svg)
parts=[text(48,50,'ML RESOURCE DRIFT SENTINEL',14,BLUE),text(48,104,'From schema contract to reviewable evidence',32),text(48,142,'Supported workflow · JSON exports in, incident context and reports out',18,MUTED)]
boxes=[(48,'01 / INPUT','Approved baseline','Current schema export','Optional upstream names'),(342,'02 / COMPARE','Validate field types','Detect schema changes','Assign review severity'),(636,'03 / REMEMBER','Dataset + baseline scope','Open / active / resolved','Count observed reopenings'),(930,'04 / REPORT','Structured JSON','Portable HTML report','Optional pipeline exit code')]
for x,label,*lines in boxes:
    parts += [rect(x,200,222,210),text(x+18,239,label,14,BLUE)]
    for i,line in enumerate(lines): parts.append(text(x+18,283+i*36,line,15))
for x in [283,577,871]:
    parts.append(f'<path d="M{x} 301h43m-10-8 10 8-10 8" stroke="{BLUE}" fill="none" stroke-width="2"/>')
parts += [text(48,466,'Single-writer local state · Lineage is investigation context, not causal attribution',18,MUTED),text(48,503,'Live DataHub integration is preserved as a historical prototype in legacy/.',16,MUTED)]
save('architecture',parts)
history=json.loads((OUT/'demo-history.json').read_text())
parts=[text(48,50,'REPRODUCIBLE DEMO / SYNTHETIC SCHEMA CHANGES',14,BLUE),text(48,104,'Repeated checks are not new incidents',32),text(48,142,'Five field changes, one recovery, and the same changes returning',18,MUTED)]
for i,stage in enumerate(history):
    x=48+i*230
    parts += [rect(x,185,214,262),text(x+16,219,stage['stage'],17),text(x+16,275,stage['changes'],42,BLUE),text(x+16,304,'active changes',15,MUTED),text(x+16,352,f"{stage['opened']} newly opened",17),text(x+16,388,f"{stage['resolved']} resolved",17)]
parts += [text(48,490,'A return after observed recovery increases each matching incident count from 1 to 2.',19,MUTED),text(48,528,'Source: docs/assets/demo-history.json · Generated by scripts/demo.py',15,MUTED)]
save('incident-lifecycle',parts,560)
report=json.loads((OUT/'demo-report.json').read_text())
counts={kind:sum(c['kind']==kind for c in report['changes']) for kind in ['removed','type_changed','added']}
parts=[text(48,50,'FIXTURE RESULTS / NO PRODUCTION PERFORMANCE CLAIMS',14,BLUE),text(48,104,'Five changes across the customer schema',32),text(48,144,f"{report['baseline_fields']} baseline fields → {report['current_fields']} current fields",20,MUTED)]
for i,(kind,count) in enumerate(counts.items()):
    y=205+i*80
    parts += [text(48,y+28,kind.replace('_',' ').title(),21),rect(255,y,count*300,40,['#fb7185','#fbbf24',BLUE][i]),text(277+count*300,y+28,count,22)]
parts += [text(48,489,'Removals and type changes require review under the default conservative policy.',19,MUTED),text(48,525,'Source: docs/assets/demo-report.json · Synthetic modifications to the supplied baseline',15,MUTED)]
save('demo-results',parts,560)
print('Generated architecture, lifecycle, and result figures.')
